import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Overlay from "@/components/Overlay";

export const metadata: Metadata = {
  title: "Faris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[var(--background)] text-[var(--foreground)] relative">
        <Overlay />
        <Navbar />
        <div className="flex justify-center">{children}</div>
      </body>
    </html>
  );
}
