import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Faris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[var(--background)] text-[var(--foreground)] flex justify-center">
        {children}
      </body>
    </html>
  );
}
